#!/usr/bin/env bash
# stampede skill: setup
# Creates a profile for a target application and optionally builds Docker image.
#
# Usage:
#   setup.sh <profile-name> <base-url> [auth-strategy]
#   setup.sh --docker
#
# Examples:
#   setup.sh myapp https://my-app.example.com
#   setup.sh myapp https://my-app.example.com form_login
#   setup.sh --docker

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
STAMPEDE_DIR="$(cd "$SCRIPT_DIR/../../../.." && pwd)"

# -- Docker build mode --------------------------------------------------------

if [[ "${1:-}" == "--docker" ]]; then
  echo "[stampede] Building Docker image..."
  docker build -t stampede -f "$STAMPEDE_DIR/Dockerfile" "$STAMPEDE_DIR"
  echo "[stampede] Docker image 'stampede' built successfully."
  exit 0
fi

# -- Profile creation mode ----------------------------------------------------

PROFILE_NAME="${1:-}"
BASE_URL="${2:-}"
AUTH_STRATEGY="${3:-none}"

if [[ -z "$PROFILE_NAME" || -z "$BASE_URL" ]]; then
  echo "Usage: setup.sh <profile-name> <base-url> [auth-strategy]"
  echo ""
  echo "Arguments:"
  echo "  profile-name    Name for the profile (e.g., myapp)"
  echo "  base-url        Target URL (e.g., https://my-app.example.com)"
  echo "  auth-strategy   Auth strategy: none, form_login, hmac, api_key, bearer (default: none)"
  echo ""
  echo "Other:"
  echo "  setup.sh --docker    Build the Docker image"
  exit 1
fi

PROFILE_FILE="$STAMPEDE_DIR/profiles/${PROFILE_NAME}.js"

if [[ -f "$PROFILE_FILE" ]]; then
  echo "[stampede] Profile already exists: $PROFILE_FILE"
  echo "[stampede] Edit it directly or delete and re-run setup."
  exit 1
fi

echo "[stampede] Creating profile: $PROFILE_NAME"
echo "[stampede] Target: $BASE_URL"
echo "[stampede] Auth: $AUTH_STRATEGY"

# Generate auth block based on strategy.
case "$AUTH_STRATEGY" in
  form_login)
    AUTH_BLOCK=$(cat << 'EOF'
{
    strategy: 'form_login',
    loginUrl: '/login',
    credentials: {
      email: __ENV.EMAIL || 'test@example.com',
      password: __ENV.PASSWORD || 'password',
    },
    csrfField: '_csrf_token',
    sessionCookieName: '_session_key',
  }
EOF
    )
    ;;
  hmac)
    AUTH_BLOCK=$(cat << 'EOF'
{
    strategy: 'hmac',
    hmac: {
      secret: __ENV.HMAC_SECRET,
      message: __ENV.HMAC_MESSAGE || 'default',
      algorithm: 'sha256',
      encoding: 'rawurl',
      tokenParam: 'token',
      params: {},
    },
  }
EOF
    )
    ;;
  api_key)
    AUTH_BLOCK=$(cat << 'EOF'
{
    strategy: 'api_key',
    apiKey: {
      header: 'X-API-Key',
      key: __ENV.API_KEY,
    },
  }
EOF
    )
    ;;
  bearer)
    AUTH_BLOCK=$(cat << 'EOF'
{
    strategy: 'bearer',
    bearer: {
      token: __ENV.AUTH_TOKEN,
    },
  }
EOF
    )
    ;;
  *)
    AUTH_BLOCK="{ strategy: 'none' }"
    ;;
esac

# Write the profile file.
cat > "$PROFILE_FILE" << PROFILE
// stampede/profiles/${PROFILE_NAME}.js
// Generated by Stampede setup. Customize as needed.

export default {
  name: '${PROFILE_NAME}',
  baseUrl: __ENV.STAMPEDE_BASE_URL || '${BASE_URL}',

  auth: ${AUTH_BLOCK},

  endpoints: {
    health: ['/healthz'],
    public: ['/'],
    admin: [],
    content: {
      index: '/',
      html: '/',
      assets: [],
    },
    mixed: [
      { path: '/healthz', weight: 0.5 },
      { path: '/', weight: 0.5 },
    ],
  },

  thresholds: {
    http_req_failed: ['rate<0.05'],
    http_req_duration: ['p(95)<3000'],
  },
};

export function contentPath(template) {
  return template;
}
PROFILE

echo "[stampede] Profile created: $PROFILE_FILE"

# Activate as target.
ln -sf "${PROFILE_NAME}.js" "$STAMPEDE_DIR/profiles/target.js"
echo "[stampede] Activated as target profile."
echo ""
echo "[stampede] Next steps:"
echo "  1. Edit $PROFILE_FILE to configure endpoints and auth details"
echo "  2. Run: k6 run $STAMPEDE_DIR/patterns/smoke.js"
